name: Build

on:
  [workflow_dispatch, push, pull_request]
  
jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        submodules: recursive

    - name: Configure stompbox
      working-directory: ${{github.workspace}}/Dependencies/stompbox/build
      run: |
        cmake.exe -G "Visual Studio 17 2022" -A x64  ..

    - name: Setup MSBuild and add to PATH
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Restore NuGet Packages
      run:
        dotnet restore
        dotnet restore .\StompboxAndroid\StompboxAndroid.csproj
    - name: Run Image Processor
      working-directory: ${{github.workspace}}
      run: |
        msbuild .\StompboxUI.sln /t:StompboxImageProcessor /p:Configuration="Release" 
        StompboxImageProcessor\bin\Release\net8.0-windows\StompboxImageProcessor.exe
        
    - name: Run MSBuild for Plugin
      working-directory: ${{github.workspace}}
      run: msbuild .\StompboxUI.sln /t:StompboxPlugin /p:Configuration=Release

    - name: Create Plugin Archive
      uses: actions/upload-artifact@v1
      with:
        name: StompboxVST3Plugin
        path: ${{github.workspace}}\StompboxPlugin\bin\Release\net8.0-windows

    - name: Run MSBuild for Windows Remote
      working-directory: ${{github.workspace}}
      run: msbuild .\StompboxUI.sln /t:StompboxRemote /p:Configuration=Release

    - name: Create Windows Remote Archive
      uses: actions/upload-artifact@v1
      with:
        name: StompboxRemote
        path: ${{github.workspace}}\StompboxRemote\bin\Release\net8.0-windows

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '17'
    
    - name: run MSBuild for Android Remote
      run: msbuild .\StompboxAndroid\StompboxAndroid.csproj /t:PackageForAndroid /p:Configuration=Debug
