name: RPi

on:
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  
jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{steps.create_release.outputs.upload_url}}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          draft: true
          tag_name: ${{github.ref}}
          release_name: Release ${{github.ref}}

  build-rpi:
    name: Build Raspberry Pi
    needs: create_release
    strategy:
      matrix:
        native_arch: [rpi4, rpi5]
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/tttapa/docker-arm-cross-toolchain:aarch64-rpi3-linux-gnu-gcc12
      options: --user root
    env:
      ARCHIVE_NAME: stompbox-jack-${{ matrix.native_arch }}.tgz
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        submodules: recursive

    - name: Build stompbox-jack
      working-directory: ${{github.workspace}}/build
      run: |
        wget https://github.com/mikeoliphant/jack-dev-rpi/raw/refs/heads/main/jackdev.tgz
        tar -xzf jackdev.tgz
        cp -r jackdev/lib/* /home/develop/opt/x-tools/aarch64-rpi3-linux-gnu/aarch64-rpi3-linux-gnu/sysroot/usr/lib/
        cp -r jackdev/include/* /home/develop/opt/x-tools/aarch64-rpi3-linux-gnu/aarch64-rpi3-linux-gnu/sysroot/usr/include
        cmake .. -DCMAKE_BUILD_TYPE="Release" -DCMAKE_TOOLCHAIN_FILE=/home/develop/opt/x-tools/aarch64-rpi3-linux-gnu/aarch64-${{ matrix.native_arch }}-linux-gnu.toolchain.cmake
        make -j4

    - name: Add Archive
      working-directory: ${{github.workspace}}/build
      run: |
        tar -czf ${{ env.ARCHIVE_NAME }} stompbox-jack/stompbox-jack
      
    - name: Upload Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./build/${{ env.ARCHIVE_NAME }}
        asset_name: ${{ env.ARCHIVE_NAME }}
        asset_content_type: application/tgz
